export const SET_START_TIME = "SET_START_TIME";
export const SET_ELAPSED_TIME = "SET_ELAPSED_TIME";
export const SET_ATTENDANCE_HISTORY = "SET_ATTENDANCE_HISTORY";
export const SET_ATTENDANCE_TYPE = "SET_ATTENDANCE_TYPE"